
server:
    port: 9040

spring: 
    r2dbc:
        url: r2dbc:pool:mysql://localhost:3306/reactive?allowPublicKeyRetrieval=true&useSSL=false
        username: arnoldkk
        password: password



